language: julia

julia:
  - 1.0

os:
  - linux
  - osx

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - rustup install nightly
  - rustup default nightly

env:
  - JULIA_PROJECT="@."

notifications:
  email: false
