authors = ["Felipe Noronha <felipenoris@gmail.com>"]
name = "JuliaPackageWithRustDep"
uuid = "b3cfa77a-c005-11e8-2503-c57ef66cec51"
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"